# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  ASH DOTFILES v5.0 — TMUX THEME: ASH DYNAMIC                             ║
# ║                                                                            ║
# ║  ██████╗░██╗░░░██╗███╗░░██╗░█████╗░███╗░░░███╗██╗░█████╗░               ║
# ║  ██╔══██╗╚██╗░██╔╝████╗░██║██╔══██╗████╗░████║██║██╔══██╗              ║
# ║  ██║░░██║░╚████╔╝░██╔██╗██║███████║██╔████╔██║██║██║░░╚═╝              ║
# ║  ██║░░██║░░╚██╔╝░░██║╚████║██╔══██║██║╚██╔╝██║██║██║░░██╗              ║
# ║  ██████╔╝░░░██║░░░██║░╚███║██║░░██║██║░╚═╝░██║██║╚█████╔╝              ║
# ║  ╚═════╝░░░░╚═╝░░░╚═╝░░╚══╝╚═╝░░╚═╝╚═╝░░░░░╚═╝╚═╝░╚════╝░              ║
# ║                                                                            ║
# ║  AUTO-GENERATED by ASH Theme Engine                                        ║
# ║  Source: ~/.config/ash/state/current-theme.json                           ║
# ║  Reload: tmux source ~/.config/tmux/themes/ash-dynamic.tmux               ║
# ║                                                                            ║
# ║  ⚡ This file is AUTOMATICALLY MANAGED by ASH.                            ║
# ║  ⚡ Manual edits will be OVERWRITTEN on next theme change.                ║
# ║  ⚡ To customize: edit ash-dark.tmux or ash-light.tmux instead.           ║
# ║                                                                            ║
# ║  Generation: {{TIMESTAMP}}                                                 ║
# ║  Active theme: {{THEME_NAME}}                                              ║
# ║  Variant: {{THEME_VARIANT}}                                                ║
# ╚══════════════════════════════════════════════════════════════════════════╝

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  🎨  DYNAMIC COLORS — Set by ASH color engine
#  All {{COLOR_*}} tokens replaced at generation time
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# ── Background layers ─────────────────────────────────────────────────────────
# ASH token: {{COLOR_CRUST}}
thm_crust="#11111b"
# ASH token: {{COLOR_MANTLE}}
thm_mantle="#181825"
# ASH token: {{COLOR_BASE}}
thm_base="#1e1e2e"
# ASH token: {{COLOR_SURFACE0}}
thm_surface0="#313244"
# ASH token: {{COLOR_SURFACE1}}
thm_surface1="#45475a"
# ASH token: {{COLOR_SURFACE2}}
thm_surface2="#585b70"

# ── Text layers ───────────────────────────────────────────────────────────────
# ASH token: {{COLOR_OVERLAY0}}
thm_overlay0="#6c7086"
# ASH token: {{COLOR_OVERLAY1}}
thm_overlay1="#7f849c"
# ASH token: {{COLOR_SUBTEXT0}}
thm_subtext0="#a6adc8"
# ASH token: {{COLOR_SUBTEXT1}}
thm_subtext1="#bac2de"
# ASH token: {{COLOR_TEXT}}
thm_text="#cdd6f4"

# ── Accent colors ─────────────────────────────────────────────────────────────
# ASH token: {{COLOR_ACCENT}} (primary)
thm_mauve="#cba6f7"
# ASH token: {{COLOR_ACCENT_ALT}}
thm_blue="#89b4fa"
# ASH token: {{COLOR_GREEN}}
thm_green="#a6e3a1"
# ASH token: {{COLOR_YELLOW}}
thm_yellow="#f9e2af"
# ASH token: {{COLOR_RED}}
thm_red="#f38ba8"
# ASH token: {{COLOR_PEACH}}
thm_peach="#fab387"
# ASH token: {{COLOR_TEAL}}
thm_teal="#94e2d5"
# ASH token: {{COLOR_LAVENDER}}
thm_lavender="#b4befe"

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  📐  SEPARATORS — Powerline (Nerd Fonts v3)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

sep_right=""
sep_left=""
sep_right_thin=""
sep_left_thin=""

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  🖥️  STATUS BAR — Dynamic layout
#
#  LEFT:  [󰊠 session] [prefix indicator] [window list →]
#  RIGHT: [← info] [󰨲 date] [󱑍 time]
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

set -g status-style "bg=$thm_mantle,fg=$thm_text"

# ── LEFT: Session pill ────────────────────────────────────────────────────────
# ┌────────────────────────────────────────────────────────────────────────────┐
# │  ██ 󰊠 session ██ ▓▒░   window tabs   ░▒▓                                  │
# └────────────────────────────────────────────────────────────────────────────┘

set -g status-left "\
#[fg=$thm_base,bg=$thm_mauve,bold] 󰊠 \
#[fg=$thm_base,bg=$thm_mauve,bold]#S \
#[fg=$thm_mauve,bg=$thm_surface1]$sep_right\
#[fg=$thm_overlay1,bg=$thm_surface1] #{?client_prefix,#[fg=$thm_yellow]⌨ ,  }\
#[fg=$thm_surface1,bg=$thm_mantle]$sep_right\
#[default] \
"

# ── RIGHT: System modules ─────────────────────────────────────────────────────
# ┌────────────────────────────────────────────────────────────────────────────┐
# │        ░▒▓█ [prefix] [zoom] [uptime] [date] [time] [host] █▓▒░            │
# └────────────────────────────────────────────────────────────────────────────┘

set -g status-right "\
#{prefix_highlight}\
#[fg=$thm_surface0,bg=$thm_mantle]$sep_left\
#[fg=$thm_yellow,bg=$thm_surface0] #{?window_zoomed_flag,󰍉 ZOOM ,}\
#[fg=$thm_overlay0,bg=$thm_surface0]  \
#(uptime -p | sed 's/up //' | sed 's/ days\\?,/d/' | sed 's/ hours\\?,/h/' | sed 's/ minutes\\?/m/')\
 \
#[fg=$thm_surface1,bg=$thm_surface0]$sep_left\
#[fg=$thm_subtext0,bg=$thm_surface1] 󰨲 \
#[fg=$thm_subtext1,bg=$thm_surface1]%a %d %b \
#[fg=$thm_surface0,bg=$thm_surface1]$sep_left\
#[fg=$thm_base,bg=$thm_surface0] \
#[fg=$thm_mantle,bg=$thm_blue,bold] 󱑍 \
#[fg=$thm_mantle,bg=$thm_blue,bold]%H:%M \
#[fg=$thm_blue,bg=$thm_mantle]$sep_left\
#[fg=$thm_overlay0,bg=$thm_mantle] 󰖡 #H \
"

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  🗂️  WINDOW TABS
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

setw -g window-status-separator ""

# ── Inactive tab ─────────────────────────────────────────────────────────────
setw -g window-status-format "\
#[fg=$thm_mantle,bg=$thm_surface0]$sep_right\
#[fg=$thm_overlay1,bg=$thm_surface0] #I \
#{?window_activity_flag,#[fg=$thm_yellow]󰐰 ,}\
#[fg=$thm_overlay1,bg=$thm_surface0]#W \
#[fg=$thm_surface0,bg=$thm_mantle]$sep_right\
"

# ── Active tab ────────────────────────────────────────────────────────────────
setw -g window-status-current-format "\
#[fg=$thm_mantle,bg=$thm_mauve]$sep_right\
#[fg=$thm_base,bg=$thm_mauve,bold] #I \
#{?window_zoomed_flag,#[fg=$thm_base]󰍉 ,}\
#[fg=$thm_base,bg=$thm_mauve,bold]#W \
#[fg=$thm_mauve,bg=$thm_mantle]$sep_right\
"

# ── Window status styles ──────────────────────────────────────────────────────
setw -g window-status-bell-style    "fg=$thm_red,bg=$thm_mantle,bold"
setw -g window-status-current-style "fg=$thm_mauve,bg=$thm_mantle,bold"
setw -g window-status-style         "fg=$thm_overlay1,bg=$thm_mantle"
setw -g window-status-activity-style "fg=$thm_yellow,bg=$thm_mantle"

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  📐  PANE BORDERS & UI
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

set -g pane-border-style              "fg=$thm_surface0"
set -g pane-active-border-style       "fg=$thm_mauve"
set -g popup-style                    "bg=$thm_base"
set -g popup-border-style             "fg=$thm_mauve,bg=$thm_base"
set -g popup-border-lines             rounded
set -g message-style                  "fg=$thm_text,bg=$thm_surface0,bold"
set -g message-command-style          "fg=$thm_mauve,bg=$thm_mantle,bold"
setw -g mode-style                    "fg=$thm_base,bg=$thm_mauve,bold"
set -g display-panes-colour           "$thm_overlay0"
set -g display-panes-active-colour    "$thm_mauve"
setw -g clock-mode-colour             "$thm_mauve"

# ASH_GENERATED=true
# ASH_VERSION=5.0.0
# ASH_THEME={{THEME_NAME}}
# ASH_TIMESTAMP={{TIMESTAMP}}