# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  🐟 ASH DOTFILES v5.0 — Starship Ultra Configuration                       ║
# ║  Dynamic prompt theming with ASH color sync & performance optimization     ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

# ── Guard: Only load in interactive sessions ─────────────────────────────────
status is-interactive || exit 0

# ── Guard: Require starship ───────────────────────────────────────────────────
command -q starship || exit 0

# ── Guard: Prevent double-loading ────────────────────────────────────────────
set --query _ash_starship_loaded && exit 0
set --global _ash_starship_loaded 1

# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  ⚙️  STARSHIP CONFIG PATH — Dynamic ASH theme sync                          ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

# Base config directory
set -l _ash_starship_dir "$HOME/.config/starship"
set -l _ash_starship_presets_dir "$HOME/.config/starship/presets"
set -l _ash_starship_dynamic "$HOME/.config/ash/cache/starship-dynamic.toml"

# ── Determine active config ───────────────────────────────────────────────────
function __ash_starship_get_config --description "Resolve active starship config path"
    # 1. Check for ASH-dynamic config (generated by theme engine)
    if test -f $_ash_starship_dynamic
        echo $_ash_starship_dynamic
        return
    end

    # 2. Check for user config
    if test -f "$_ash_starship_dir/starship.toml"
        echo "$_ash_starship_dir/starship.toml"
        return
    end

    # 3. Use XDG default
    if test -f "$HOME/.config/starship.toml"
        echo "$HOME/.config/starship.toml"
        return
    end

    # 4. Fallback — no config (starship will use its built-in defaults)
    echo ""
end

set -l _starship_config (__ash_starship_get_config)

if test -n "$_starship_config"
    set --export STARSHIP_CONFIG $_starship_config
end

# Cache file for faster subsequent shell starts
set --export STARSHIP_CACHE "$HOME/.cache/starship"
mkdir -p $STARSHIP_CACHE 2>/dev/null

# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  🎨 DYNAMIC THEME GENERATION                                                ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

function __ash_starship_generate_theme --description "Generate starship TOML from ASH theme colors"
    set -l state_file "$HOME/.local/share/ash/state/current-theme.json"
    set -l output $_ash_starship_dynamic

    # Default Catppuccin Mocha palette
    set -l c_base    "#1e1e2e"
    set -l c_surface "#313244"
    set -l c_text    "#cdd6f4"
    set -l c_subtext "#a6adc8"
    set -l c_rosewater "#f5e0dc"
    set -l c_flamingo  "#f2cdcd"
    set -l c_pink      "#f5c2e7"
    set -l c_mauve     "#cba6f7"
    set -l c_red       "#f38ba8"
    set -l c_maroon    "#eba0ac"
    set -l c_peach     "#fab387"
    set -l c_yellow    "#f9e2af"
    set -l c_green     "#a6e3a1"
    set -l c_teal      "#94e2d5"
    set -l c_sky       "#89dceb"
    set -l c_blue      "#89b4fa"
    set -l c_lavender  "#b4befe"

    # Override with current ASH theme if available
    if test -f $state_file && command -q jq
        set -l parsed (jq -r '
            .colors |
            "c_base=\(.base // "#1e1e2e")\n"
            + "c_surface=\(.surface0 // "#313244")\n"
            + "c_text=\(.text // "#cdd6f4")\n"
            + "c_subtext=\(.subtext1 // "#a6adc8")\n"
            + "c_mauve=\(.mauve // "#cba6f7")\n"
            + "c_red=\(.red // "#f38ba8")\n"
            + "c_peach=\(.peach // "#fab387")\n"
            + "c_yellow=\(.yellow // "#f9e2af")\n"
            + "c_green=\(.green // "#a6e3a1")\n"
            + "c_sky=\(.sky // "#89dceb")\n"
            + "c_blue=\(.blue // "#89b4fa")\n"
            + "c_lavender=\(.lavender // "#b4befe")"
        ' $state_file 2>/dev/null)

        for pair in $parsed
            set -l key (string split --max 1 = $pair)[1]
            set -l val (string split --max 1 = $pair)[2]
            set $key $val
        end
    end

    # ── Write TOML ────────────────────────────────────────────────────────────
    mkdir -p (dirname $output) 2>/dev/null

    printf '%s\n' \
        '# ╔══════════════════════════════════════════════════╗' \
        '# ║  Auto-generated by ASH Theme Engine v5.0         ║' \
        '# ║  Do not edit — changes will be overwritten       ║' \
        '# ╚══════════════════════════════════════════════════╝' \
        '' \
        'format = """' \
        '\$username\$hostname\$localip\$shlvl\$singularity\$kubernetes\$directory\$vcsh\$fossil_branch\$git_branch\$git_commit\$git_state\$git_metrics\$git_status\$hg_branch\$pijul_channel\$docker_context\$package\$c\$cmake\$cobol\$daml\$dart\$deno\$dotnet\$elixir\$elm\$erlang\$fennel\$golang\$guix_shell\$haskell\$haxe\$helm\$java\$julia\$kotlin\$gradle\$lua\$nim\$nodejs\$ocaml\$opa\$perl\$php\$pulumi\$purescript\$python\$raku\$rlang\$red\$ruby\$rust\$scala\$swift\$terraform\$vlang\$vagrant\$zig\$buf\$nix_shell\$conda\$meson\$spack\$memory_usage\$aws\$gcloud\$openstack\$azure\$env_var\$crystal\$custom\$sudo\$cmd_duration\$line_break\$jobs\$battery\$time\$status\$os\$container\$shell\$character"""' \
        '' \
        "palette = 'ash_dynamic'" \
        '' \
        '[palettes.ash_dynamic]' \
        "base     = '$c_base'" \
        "surface  = '$c_surface'" \
        "text     = '$c_text'" \
        "subtext  = '$c_subtext'" \
        "mauve    = '$c_mauve'" \
        "red      = '$c_red'" \
        "peach    = '$c_peach'" \
        "yellow   = '$c_yellow'" \
        "green    = '$c_green'" \
        "sky      = '$c_sky'" \
        "blue     = '$c_blue'" \
        "lavender = '$c_lavender'" \
        '' \
        '[character]' \
        'success_symbol = "[❯](bold green)"' \
        'error_symbol   = "[❯](bold red)"' \
        'vimcmd_symbol  = "[❮](bold mauve)"' \
        '' \
        '[directory]' \
        'style                     = "bold blue"' \
        'read_only                 = " 󰌾"' \
        'truncation_length         = 4' \
        'truncate_to_repo          = true' \
        'fish_style_pwd_dir_length = 1' \
        'home_symbol               = "~"' \
        '' \
        '[git_branch]' \
        'symbol    = " "' \
        'style     = "bold mauve"' \
        'format    = "[$symbol$branch(:$remote_branch)]($style) "' \
        '' \
        '[git_status]' \
        'format    = "([$all_status$ahead_behind]($style)) "' \
        'style     = "bold red"' \
        'ahead     = "⇡\${count}"' \
        'diverged  = "⇕⇡\${ahead_count}⇣\${behind_count}"' \
        'behind    = "⇣\${count}"' \
        'staged    = "[+\${count}](green)"' \
        'modified  = "[~\${count}](yellow)"' \
        'deleted   = "[-\${count}](red)"' \
        'untracked = "[?\${count}](sky)"' \
        '' \
        '[git_metrics]' \
        'added_style   = "bold green"' \
        'deleted_style = "bold red"' \
        'disabled      = false' \
        '' \
        '[nodejs]' \
        'symbol  = " "' \
        'style   = "bold green"' \
        'format  = "[$symbol($version )]($style)"' \
        '' \
        '[python]' \
        'symbol         = " "' \
        'style          = "bold yellow"' \
        'format         = "[${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)"' \
        '' \
        '[rust]' \
        'symbol  = " "' \
        'style   = "bold peach"' \
        'format  = "[$symbol($version )]($style)"' \
        '' \
        '[golang]' \
        'symbol  = " "' \
        'style   = "bold sky"' \
        'format  = "[$symbol($version )]($style)"' \
        '' \
        '[lua]' \
        'symbol  = " "' \
        'style   = "bold blue"' \
        'format  = "[$symbol($version )]($style)"' \
        '' \
        '[java]' \
        'symbol  = " "' \
        'style   = "bold red"' \
        'format  = "[${symbol}(${version} )]($style)"' \
        '' \
        '[kotlin]' \
        'symbol  = " "' \
        'style   = "bold mauve"' \
        'format  = "[$symbol($version )]($style)"' \
        '' \
        '[docker_context]' \
        'symbol  = " "' \
        'style   = "bold sky"' \
        'format  = "[$symbol$context]($style) "' \
        '' \
        '[kubernetes]' \
        'symbol   = "󱃾 "' \
        'style    = "bold blue"' \
        'format   = "[$symbol$context( \\($namespace\\))]($style) "' \
        'disabled = false' \
        '' \
        '[aws]' \
        'symbol  = " "' \
        'style   = "bold peach"' \
        'format  = "[$symbol($profile )(\\($region\\) )(\\[$duration\\] )]($style)"' \
        '' \
        '[gcloud]' \
        'symbol  = " "' \
        'style   = "bold blue"' \
        'format  = "[$symbol$account(@$domain)(\\($region\\))]($style) "' \
        '' \
        '[terraform]' \
        'symbol  = "󱁢 "' \
        'style   = "bold mauve"' \
        'format  = "[$symbol$workspace]($style) "' \
        '' \
        '[nix_shell]' \
        'symbol  = " "' \
        'style   = "bold blue"' \
        'format  = "[$symbol$state( \\($name\\))]($style) "' \
        '' \
        '[memory_usage]' \
        'symbol    = " "' \
        'style     = "bold red"' \
        'threshold = 80' \
        'format    = "$symbol[${ram}( | ${swap})]($style) "' \
        'disabled  = false' \
        '' \
        '[battery]' \
        'full_symbol        = "󰁹 "' \
        'charging_symbol    = "󰂄 "' \
        'discharging_symbol = "󰂃 "' \
        'unknown_symbol     = "󰁽 "' \
        'empty_symbol       = "󰂎 "' \
        '' \
        '[[battery.display]]' \
        'threshold = 10' \
        'style     = "bold red"' \
        '' \
        '[[battery.display]]' \
        'threshold = 30' \
        'style     = "bold yellow"' \
        '' \
        '[[battery.display]]' \
        'threshold = 100' \
        'style     = "bold green"' \
        '' \
        '[cmd_duration]' \
        'min_time             = 2000' \
        'style                = "bold yellow"' \
        'show_milliseconds    = false' \
        'format               = "[$duration]($style) "' \
        'show_notifications   = false' \
        '' \
        '[status]' \
        'style    = "bold red"' \
        'symbol   = " "' \
        'success_symbol = ""' \
        'format   = "[$symbol$status]($style) "' \
        'map_symbol = true' \
        'disabled = false' \
        '' \
        '[time]' \
        'disabled      = false' \
        'style         = "bold subtext"' \
        'format        = "[$time]($style) "' \
        'time_format   = "%H:%M"' \
        '' \
        '[username]' \
        'style_user  = "bold mauve"' \
        'style_root  = "bold red"' \
        'format      = "[$user]($style)[@](bold subtext)"' \
        'show_always = false' \
        '' \
        '[hostname]' \
        'ssh_only  = true' \
        'style     = "bold green"' \
        'format    = "[$hostname]($style) "' \
        '' \
        '[jobs]' \
        'symbol   = " "' \
        'style    = "bold blue"' \
        'number_threshold = 1' \
        'format   = "[$symbol$number]($style) "' \
        '' \
        '[sudo]' \
        'symbol   = "󰞋 "' \
        'style    = "bold red"' \
        'format   = "[$symbol]($style)"' \
        'disabled = false' \
        '' \
        '[shell]' \
        'fish_indicator   = " "' \
        'bash_indicator   = " "' \
        'zsh_indicator    = " "' \
        'disabled         = false' \
        'style            = "bold subtext"' \
        'format           = "[$indicator]($style)"' \
        '' \
        '[os]' \
        'disabled = false' \
        'style    = "bold text"' \
        '' \
        '[os.symbols]' \
        'Arch     = " "' \
        'Fedora   = " "' \
        'NixOS    = " "' \
        'Ubuntu   = " "' \
        'Debian   = " "' \
        'openSUSE = " "' \
        'Void     = " "' \
        'Gentoo   = " "' \
        'Macos    = " "' \
        'Windows  = " "' \
        'Linux    = " "' \
        > $output

    echo $output
end

# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  🔃 THEME SYNC EVENT HANDLER                                                ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

function __ash_starship_on_theme_change --on-event ash_theme_changed \
    --description "Regenerate starship config on ASH theme change"

    # Regenerate dynamic config
    set -l new_config (__ash_starship_generate_theme)

    # Update STARSHIP_CONFIG live
    set --global --export STARSHIP_CONFIG $new_config

    # Force starship to reload (it respects env changes on next prompt)
    set --erase _ash_starship_loaded
end

# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  🚀 INITIALIZATION                                                          ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

# Generate dynamic config if it doesn't exist or is older than the theme state
set -l _state "$HOME/.local/share/ash/state/current-theme.json"
set -l _need_gen 0

if not test -f $_ash_starship_dynamic
    set _need_gen 1
else if test -f $_state
    # Regenerate if theme is newer than current starship config
    set -l theme_mtime (stat -c %Y $_state 2>/dev/null; or echo 0)
    set -l conf_mtime  (stat -c %Y $_ash_starship_dynamic 2>/dev/null; or echo 0)
    test $theme_mtime -gt $conf_mtime && set _need_gen 1
end

if test $_need_gen -eq 1
    set -l generated (__ash_starship_generate_theme 2>/dev/null)
    test -n "$generated" && set --export STARSHIP_CONFIG $generated
end

# ── Initialize starship prompt ────────────────────────────────────────────────
starship init fish | source

# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  🔧 PRESET SWITCHER                                                         ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

function starship_preset --description "Switch starship preset"
    set -l preset $argv[1]
    set -l presets_dir "$HOME/.config/starship/presets"

    if test -z "$preset"
        # List available presets
        echo ""
        echo "  Available starship presets:"
        echo ""

        set -l presets default minimal powerline nerdfont-symbols bracketed \
            tokyo-night gruvbox catppuccin ash-dynamic

        for p in $presets
            set -l active ""
            test "$STARSHIP_CONFIG" = "$presets_dir/$p.toml" && set active " ← active"
            echo "    • $p$active"
        end

        echo ""
        echo "  Usage: starship_preset <name>"
        echo ""
        return
    end

    switch $preset
        case ash ash-dynamic dynamic
            # Use ASH dynamic theme
            set -l new (__ash_starship_generate_theme)
            set --global --export STARSHIP_CONFIG $new
            echo "  ✓ Switched to ASH dynamic theme"

        case '*'
            # Load from presets directory
            set -l preset_file "$presets_dir/$preset.toml"
            if test -f $preset_file
                set --global --export STARSHIP_CONFIG $preset_file
                echo "  ✓ Switched to preset: $preset"
            else
                # Try starship's built-in presets
                set -l tmp (mktemp /tmp/starship-preset-XXXXXX.toml)
                if starship preset $preset -o $tmp 2>/dev/null
                    set --global --export STARSHIP_CONFIG $tmp
                    echo "  ✓ Applied built-in preset: $preset"
                else
                    echo "  ✗ Preset not found: $preset" >&2
                    return 1
                end
            end
    end
end

# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  📊 STARSHIP UTILITIES                                                      ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

function starship_bench --description "Benchmark starship prompt render time"
    echo ""
    echo "  ⏱️  Benchmarking starship prompt..."
    echo ""
    starship timings
    echo ""
end

function starship_debug --description "Show starship debug info"
    echo ""
    echo "  🔍 Starship debug info:"
    echo ""
    echo "  Config:  $STARSHIP_CONFIG"
    echo "  Cache:   $STARSHIP_CACHE"
    echo "  Version: "(starship --version)
    echo ""
    echo "  Module status:"
    starship explain
end

# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  ⌨️  ABBREVIATIONS                                                           ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

abbr --add ssp    'starship_preset'
abbr --add ssb    'starship_bench'
abbr --add ssd    'starship_debug'
abbr --add ssgen  '__ash_starship_generate_theme'
abbr --add ssconf 'echo $STARSHIP_CONFIG'
abbr --add ssedit 'nvim $STARSHIP_CONFIG'