---
extends: default

rules:
  braces: disable
  brackets: disable
  colons: disable
  comments: disable
  comments-indentation: disable
  document-start: disable
  empty-lines: disable
  indentation:
    check-multi-line-strings: false
  key-duplicates: disable
  line-length: disable
  new-line-at-end-of-file: disable
  trailing-spaces: disable
  truthy:
    check-keys: false
