version: '3'

tasks:
  default:
    cmds:
      - task --list
  install:
    cmds:
      - bash install.sh
  test:
    cmds:
      - bash .git-hooks/run-tests.sh
  lint:
    cmds:
      - bash .git-hooks/validate-theme.sh
      - bash .git-hooks/validate-plugin.sh
  format:
    cmds:
      - bash .git-hooks/format-scripts.sh
  doctor:
    cmds:
      - bash scripts/health/doctor.sh
