# ╔═══════════════════════════════════════════════════════════════════════════════╗
# ║           ASH DOTFILES v3.0 — GITIGNORE FUNCTION                           ║
# ║           Generate .gitignore from gitignore.io                            ║
# ╚═══════════════════════════════════════════════════════════════════════════════╝

function gitignore -d "Generate .gitignore from gitignore.io"
    if test (count $argv) -eq 0
        echo "Usage: gitignore [language/os/framework...]"
        echo ""
        echo "Examples:"
        echo "  gitignore python"
        echo "  gitignore node react"
        echo "  gitignore python django linux macos"
        echo "  gitignore --list"
        return 0
    end

    if test "$argv[1]" = "--list" -o "$argv[1]" = "-l"
        # List available templates
        echo "Fetching available templates..."
        curl -sL "https://www.toptal.com/developers/gitignore/api/list" 2>/dev/null \
            | tr ',' '\n' \
            | column 2>/dev/null \
            || echo "Could not fetch list"
        return 0
    end

    set -l types (string join "," $argv)
    set -l url "https://www.toptal.com/developers/gitignore/api/$types"

    echo "# Generated by gitignore.io — $types" > /tmp/gitignore-preview

    echo "Fetching .gitignore for: $types"
    set -l content (curl -sL "$url" 2>/dev/null)

    if test $status -ne 0 -o -z "$content"
        echo "Failed to fetch gitignore template"
        return 1
    end

    # Show preview
    echo ""
    echo "Preview (first 20 lines):"
    echo "$content" | head -20
    echo "..."
    echo ""

    # Ask to save
    read -P "Save to .gitignore? [Y/n]: " confirm
    if test (string lower "$confirm") != "n"
        echo "$content" > .gitignore
        echo (set_color green)"✓"(set_color normal)" Saved to .gitignore"
    else
        echo "Not saved"
    end
end

complete -c gitignore -x -d "Language/framework/OS name"