#!/usr/bin/env bash
# ╔═══════════════════════════════════════════════════════════════════════════════╗
# ║  ASH THEME — clone.sh                                                         ║
# ║  Copy a theme into your own collection, where you can edit it freely           ║
# ╚═══════════════════════════════════════════════════════════════════════════════╝
# Sourced by theme.sh; defines only.

theme::clone::help() {
    cat <<EOF
${BOLD}${ASH_PRIMARY}USAGE${RST}
  ${ASH_ACCENT}ash theme clone${RST} <source> [new-slug] [options]

${BOLD}${ASH_PRIMARY}DESCRIPTION${RST}
  Copies a theme into ${ASH_ACCENT}\$XDG_DATA_HOME/ash/themes${RST} and rewrites its
  identity. The catalogue ships with the repo and is regenerated by
  scripts/theme/generate-library.sh, so hand edits there are lost at the next
  regeneration — cloning first is what makes a built-in theme editable.

  User themes shadow catalogue themes of the same slug, so a clone that keeps
  the original slug simply takes over the name.

${BOLD}${ASH_PRIMARY}OPTIONS${RST}
  ${ASH_MUTED}--name NAME${RST}     Display name for the clone
  ${ASH_MUTED}--variant dark|light${RST}
  ${ASH_MUTED}--family NAME${RST}   Family for grouping in the catalogue
  ${ASH_MUTED}--force${RST}         Overwrite an existing user theme
  ${ASH_MUTED}--dry-run, -n${RST}   Show what would be written
  ${ASH_MUTED}--json${RST}          Machine-readable output

${BOLD}${ASH_PRIMARY}EXAMPLES${RST}
  ${ASH_MUTED}ash theme clone nord nord-mine${RST}
  ${ASH_MUTED}ash theme clone catppuccin-mocha mocha-soft --name "Mocha Soft"${RST}
EOF
}

theme::clone() {
    local src="" dest="" name="" variant="" family="" force=0 dry=0
    local -a args=("$@")

    while (( $# )); do
        case "$1" in
            --name)      name="${2:-}"; shift 2 ;;
            --variant)   variant="${2:-}"; shift 2 ;;
            --family)    family="${2:-}"; shift 2 ;;
            --force|-f)  force=1; shift ;;
            --dry-run|-n) dry=1; shift ;;
            --json)      export ASH_FLAG_JSON_OUTPUT=1; shift ;;
            -h|--help)   theme::clone::help; return 0 ;;
            -*)          ash_log_error "Unknown option: $1"; theme::clone::help; return 2 ;;
            *)           if [[ -z "$src" ]]; then src="$1"; else dest="$1"; fi; shift ;;
        esac
    done

    [[ -n "$src" ]] || { ash_log_error "Which theme should I clone?"; theme::clone::help; return 2; }

    local src_file
    if ! src_file="$(theme::resolve "$src")"; then
        ash_log_error "No such theme: $src"
        return 1
    fi

    local src_slug
    src_slug="$(jq -r '.slug // empty' "$src_file" 2>/dev/null)"
    [[ -n "$src_slug" ]] || src_slug="$(basename "$src_file" .json)"

    # Default destination: <slug>-copy, bumped to -copy-2, -3 … rather than
    # silently overwriting something the user already has.
    if [[ -z "$dest" ]]; then
        dest="${src_slug}-copy"
        local n=2
        while [[ -f "${THEME_USER_DIR}/${dest}.json" ]]; do
            dest="${src_slug}-copy-${n}"
            (( n++ )) || true
        done
    fi

    dest="$(ash_generate_slug "$dest" 2>/dev/null || tr '[:upper:]' '[:lower:]' <<<"$dest" | tr -c 'a-z0-9-' '-')"
    dest="${dest%-}"
    [[ -n "$dest" ]] || { ash_log_error "That slug has no usable characters"; return 2; }

    local dest_file="${THEME_USER_DIR}/${dest}.json"

    [[ -n "$name" ]]    || name="$(jq -r '.name // empty' "$src_file" 2>/dev/null) copy"
    [[ -n "$variant" ]] || variant="$(jq -r '.variant // "dark"' "$src_file" 2>/dev/null)"
    [[ -n "$family" ]]  || family="$(jq -r '.family // "other"' "$src_file" 2>/dev/null)"

    if [[ "$variant" != "dark" && "$variant" != "light" ]]; then
        ash_log_error "--variant must be dark or light (got: $variant)"
        return 2
    fi

    local existed=0
    [[ -f "$dest_file" ]] && existed=1
    if (( existed && ! force )); then
        ash_log_error "User theme '${dest}' already exists."
        printf '  %sPass --force to overwrite it.%s\n' "${ASH_MUTED}" "${RST}" >&2
        return 1
    fi

    if [[ "${ASH_FLAG_JSON_OUTPUT:-0}" -eq 1 ]]; then
        jq -n --arg from "$src_file" --arg from_slug "$src_slug" \
              --arg to "$dest_file" --arg slug "$dest" \
              --arg name "$name" --arg variant "$variant" --arg family "$family" \
              --argjson existed "$existed" --argjson dry "$dry" \
              '{source: $from, source_slug: $from_slug, slug: $slug, name: $name,
                variant: $variant, family: $family, file: $to,
                overwrote: ($existed == 1), dry_run: ($dry == 1)}'
        (( dry )) && return 0
    fi

    if (( dry )); then
        printf '\n  %sWould write %s%s\n' "${ASH_MUTED}" "$dest_file" "${RST}"
        printf '  %s  slug=%s  name=%s  variant=%s  family=%s%s\n\n' \
            "${ASH_MUTED}" "$dest" "$name" "$variant" "$family" "${RST}"
        return 0
    fi

    mkdir -p "$THEME_USER_DIR"

    # Rewrite identity fields in one pass. The colours pass through untouched —
    # a clone is a rename, not a recolour; `theme edit` exists for that.
    jq -S --arg slug "$dest" --arg name "$name" --arg variant "$variant" \
          --arg family "$family" \
          '.slug = $slug | .name = $name | .variant = $variant | .family = $family' \
          "$src_file" > "${dest_file}.tmp" || {
        ash_log_error "Could not write the clone"
        rm -f "${dest_file}.tmp"
        return 1
    }
    mv "${dest_file}.tmp" "$dest_file"

    theme::record "$dest" clone

    if [[ "${ASH_FLAG_JSON_OUTPUT:-0}" -eq 1 ]]; then return 0; fi

    printf '\n  %s✅ Cloned%s %s → %s%s%s\n' \
        "${ASH_SUCCESS}" "${RST}" "$src_slug" "${BOLD}${ASH_ACCENT}" "$dest" "${RST}"
    printf '  %s   %s%s\n\n' "${ASH_MUTED}" "$dest_file" "${RST}"
    printf '  %sEdit it:  ash theme edit %s --slot accent=#8fbcbb%s\n\n' \
        "${ASH_MUTED}" "$dest" "${RST}"
}
