#!/usr/bin/env bash
# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║                                                                              ║
# ║  🎨 ASH THEME — command dispatcher                                           ║
# ║      ASH DOTFILES v5.0 OMEGA                                                ║
# ║                                                                              ║
# ║  The front door to the theming subsystem: the colour engine, the 361-theme   ║
# ║  catalogue, the 25 config templates, and the store.                         ║
# ║                                                                              ║
# ║  Each subcommand lives in its own file next to this one and defines          ║
# ║  theme::<name>() plus a theme::<name>::help(). Submodules are sourced only   ║
# ║  when the subcommand is used, so `ash theme list` does not pay to parse the  ║
# ║  AI and store modules.                                                      ║
# ║                                                                              ║
# ║  Layout follows commands/snapshot/, which is the house pattern for a         ║
# ║  multi-file command.                                                        ║
# ║                                                                              ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
set -euo pipefail
IFS=$'\n\t'

# ── Locate the repo ───────────────────────────────────────────────────────────
_THEME_CMD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_THEME_LIB_DIR="${_THEME_CMD_DIR}/../../lib"
_THEME_ENGINE_DIR="${_THEME_CMD_DIR}/../../engines/color-engine"
_THEME_ROOT="$(cd "${_THEME_CMD_DIR}/../../.." && pwd)"

# ── Libraries ─────────────────────────────────────────────────────────────────
# Each guards itself, so this is a no-op when the dispatcher already loaded them.
for _lib in colors logger utils template-engine box-renderer table-renderer; do
    [[ -r "${_THEME_LIB_DIR}/${_lib}.sh" ]] && source "${_THEME_LIB_DIR}/${_lib}.sh"
done
unset _lib

# ── Colour engine ─────────────────────────────────────────────────────────────
# In dependency order: oklch/hsl are the maths, contrast and harmonize build on
# them, palette and generate build on those, and wcag-validate sits on top.
for _mod in oklch hsl contrast-check harmonize palette generate extract gradient \
            material-you wcag-validate; do
    [[ -r "${_THEME_ENGINE_DIR}/${_mod}.sh" ]] && source "${_THEME_ENGINE_DIR}/${_mod}.sh"
done
unset _mod

# ─────────────────────────────────────────────────────────────────────────────
# Paths
#
# The catalogue ships with the repo and is read-only in effect — it is
# regenerated by scripts/theme/generate-library.sh, so hand edits are lost. User
# themes live under XDG_DATA_HOME and are searched first, which is what makes
# `ash theme create` + `ash theme apply` work without touching the checkout.
# ─────────────────────────────────────────────────────────────────────────────
THEME_CATALOGUE_DIR="${ASH_THEMES_DIR:-${_THEME_ROOT}/themes}"
THEME_USER_DIR="${ASH_DATA_HOME:-${XDG_DATA_HOME:-$HOME/.local/share}/ash}/themes"
THEME_FAVORITES_FILE="${ASH_DATA_HOME:-${XDG_DATA_HOME:-$HOME/.local/share}/ash}/theme-favorites.json"
THEME_HISTORY_FILE="${ASH_STATE_HOME:-${XDG_STATE_HOME:-$HOME/.local/state}/ash}/theme-history.jsonl"
THEME_CURRENT_FILE="${ASH_CONFIG_HOME:-${XDG_CONFIG_HOME:-$HOME/.config}/ash}/current-theme.json"
THEME_TEMPLATE_DIR="${_THEME_ENGINE_DIR}/templates"
THEME_TRASH_DIR="${ASH_DATA_HOME:-${XDG_DATA_HOME:-$HOME/.local/share}/ash}/themes/.trash"

# Slots in presentation order: surface tones dark→light, then foregrounds, then
# accents. This is the order a reader scans a palette in.
THEME_SLOT_ORDER=(
    crust mantle base surface overlay
    text subtext
    accent mint sky gold rose violet
)

# ─────────────────────────────────────────────────────────────────────────────
# Shared helpers
# ─────────────────────────────────────────────────────────────────────────────

# Resolve a name to a catalogue file. Accepts a slug, a display name in any
# case, or an explicit path. User themes shadow catalogue themes of the same
# slug, so a locally created "nord" wins over the built-in one.
theme::resolve() {
    local want="$1" cand

    [[ -f "$want" ]] && { printf '%s' "$want"; return 0; }

    for cand in "${THEME_USER_DIR}/${want}.json" \
                "${THEME_CATALOGUE_DIR}/${want}.json" \
                "${THEME_CATALOGUE_DIR}/presets/${want}.json"; do
        [[ -f "$cand" ]] && { printf '%s' "$cand"; return 0; }
    done

    # Case-insensitive match on display name, then slug. Covers both
    # directories so a user theme is found by name too.
    local d f slug name
    for d in "$THEME_USER_DIR" "$THEME_CATALOGUE_DIR"; do
        [[ -d "$d" ]] || continue
        for f in "$d"/*.json; do
            [[ -f "$f" ]] || continue
            slug="$(jq -r '.slug // empty' "$f" 2>/dev/null)"
            name="$(jq -r '.name // empty' "$f" 2>/dev/null)"
            if [[ "${slug,,}" == "${want,,}" || "${name,,}" == "${want,,}" ]]; then
                printf '%s' "$f"; return 0
            fi
        done
    done

    return 1
}

# Every theme file, user themes first so they shadow the catalogue.
theme::files() {
    local d f
    for d in "$THEME_USER_DIR" "$THEME_CATALOGUE_DIR"; do
        [[ -d "$d" ]] || continue
        for f in "$d"/*.json; do
            [[ -f "$f" ]] && printf '%s\n' "$f"
        done
    done
}

# slug<TAB>name<TAB>variant<TAB>family<TAB>seed<TAB>path for every theme,
# sorted by family then slug.
#
# One jq pass over the whole set rather than one per file: 361 files spawned as
# 361 processes takes seconds; this takes milliseconds.
theme::index() {
    local -a files=()
    local f
    while IFS= read -r f; do files+=("$f"); done < <(theme::files)
    (( ${#files[@]} )) || return 0

    jq -r --arg p "$PWD" '
        [ (.slug // ""), (.name // ""), (.variant // "dark"), (.family // "other"),
          (.seed // ""), (input_filename) ] | @tsv
    ' "${files[@]}" 2>/dev/null | sort -t$'\t' -k4,4 -k1,1
}

# Load a theme file into any palette nameref. Prefers the engine's loader, which
# understands both the nested document and a bare palette, and falls back to a
# jq read so `show` works from a bare checkout.
theme::load() {
    local file="$1"
    local -n ref="$2"

    if declare -f _ash_palette_load_file >/dev/null 2>&1; then
        _ash_palette_load_file "$file" ref
        return 0
    fi

    local k v
    while IFS=$'\t' read -r k v; do
        [[ -n "$k" ]] && ref["$k"]="$v"
    done < <(jq -r '
        (if has("colors") then .colors else . end)
        | to_entries | map(select(.value | type == "string" and test("^#[0-9a-fA-F]{6}$")))
        | .[] | "\(.key)\t\(.value)"' "$file" 2>/dev/null)
}

# A filled block drawn in the colour itself, so the swatch IS the hex. Returns
# blanks rather than escape codes when colour is off, keeping the column width
# consistent in logs and `--json` output.
theme::swatch() {
    local hex="$1" width="${2:-12}"
    [[ -n "$hex" ]] || { printf '%*s' "$width" ''; return 0; }
    if [[ "${ASH_FLAG_NO_COLOR:-0}" -eq 1 || ! -t 1 ]]; then
        printf '%*s' "$width" ''; return 0
    fi

    local r g b bar
    r=$(( 16#${hex:1:2} )); g=$(( 16#${hex:3:2} )); b=$(( 16#${hex:5:2} ))
    bar="$(printf '%*s' "$width" '' | tr ' ' '█')"
    printf '\033[38;2;%d;%d;%dm%s\033[0m' "$r" "$g" "$b" "$bar"
}

# Is this one of the 13 palette slots?
#
# Written as an explicit loop rather than `[[ " ${THEME_SLOT_ORDER[*]} " == ... ]]`:
# bash joins an array with the FIRST character of IFS, and the dispatcher sets
# IFS=$'\n\t' — so the joined string is newline-separated and no space-delimited
# pattern ever matches. That silently rejected every valid slot name.
theme::is_slot() {
    local want="$1" s
    for s in "${THEME_SLOT_ORDER[@]}"; do
        [[ "$s" == "$want" ]] && return 0
    done
    return 1
}

# Count with correct pluralisation.
theme::plural() {
    local n="$1" one="$2" many="${3:-}"
    if [[ -z "$many" ]]; then
        case "$one" in
            *y) many="${one%y}ies" ;;
            *s|*x|*ch|*sh) many="${one}es" ;;
            *) many="${one}s" ;;
        esac
    fi
    if [[ "$n" == "1" ]]; then printf '%s %s' "$n" "$one"; else printf '%s %s' "$n" "$many"; fi
}

# Write a palette document, preserving metadata. Always writes the nested shape
# so every consumer sees one layout.
theme::save() {
    local file="$1"
    local -n ref="$2"
    local -A meta=()
    shift 2 || true

    # Carry forward any existing metadata, then apply overrides.
    if [[ -f "$file" ]] && jq -e 'type == "object"' "$file" >/dev/null 2>&1; then
        local k v
        while IFS=$'\t' read -r k v; do meta["$k"]="$v"; done < <(
            jq -r 'to_entries
                   | map(select(.value | type == "string"))
                   | .[] | "\(.key)\t\(.value)"' "$file" 2>/dev/null)
    fi

    local pair
    for pair in "$@"; do
        meta["${pair%%=*}"]="${pair#*=}"
    done

    mkdir -p "$(dirname "$file")"

    # Build the colours object, then merge the metadata over it.
    local colors_json
    colors_json="$(ash_palette_render_json ref 2>/dev/null)" || return 1

    local meta_json='{}'
    local key
    for key in "${!meta[@]}"; do
        [[ -n "${meta[$key]}" ]] || continue
        meta_json="$(jq -c --arg k "$key" --arg v "${meta[$key]}" '. + {($k): $v}' <<<"$meta_json")"
    done

    jq -S --argjson c "$colors_json" --argjson m "$meta_json" \
       '$m + {colors: $c}' <<<"{}" > "${file}.tmp" || return 1
    mv "${file}.tmp" "$file"
}

# Record a theme change, so `ash theme history` has something to show.
theme::record() {
    local slug="$1" action="${2:-apply}"
    mkdir -p "$(dirname "$THEME_HISTORY_FILE")" 2>/dev/null || true
    jq -cn --arg slug "$slug" --arg action "$action" \
           --arg at "$(date -Is 2>/dev/null || date)" \
           '{slug: $slug, action: $action, at: $at}' >> "$THEME_HISTORY_FILE" 2>/dev/null || true
}

# Read the currently applied theme slug, if any.
theme::current() {
    [[ -f "$THEME_CURRENT_FILE" ]] || return 1
    jq -r '.slug // empty' "$THEME_CURRENT_FILE" 2>/dev/null
}

# Mark a theme as applied.
theme::set_current() {
    local file="$1" slug="$2"
    mkdir -p "$(dirname "$THEME_CURRENT_FILE")" 2>/dev/null || true
    jq -n --arg slug "$slug" --arg file "$file" \
          --arg at "$(date -Is 2>/dev/null || date)" \
          '{slug: $slug, file: $file, at: $at}' > "$THEME_CURRENT_FILE" 2>/dev/null || true
}

# ─────────────────────────────────────────────────────────────────────────────
# Subcommand registry
#
# key → "file|emoji description". Keeping this as a table rather than a case
# statement means the help screen and the dispatcher cannot disagree, which is
# how the parent command's help drifted from its ASH_COMMANDS table.
# ─────────────────────────────────────────────────────────────────────────────
declare -gA THEME_SUBCOMMANDS=(
    [list]="list.sh|📋 Browse the theme catalogue"
    [colors]="colors.sh|🎨 Show a theme's palette"
    [preview]="preview.sh|👁  Render a preview of a theme"
    [apply]="apply.sh|⚡ Apply a theme to your configs"
    [create]="create.sh|✨ Create a theme from a seed colour"
    [clone]="clone.sh|🧬 Duplicate an existing theme"
    [delete]="delete.sh|🗑  Delete a user theme"
    [edit]="edit.sh|✏️  Edit theme metadata"
    [import]="import.sh|📥 Import a theme file"
    [export]="export.sh|📤 Export a theme file"
    [random]="random.sh|🎲 Apply a random theme"
    [pick]="pick.sh|🎯 Interactively pick a theme"
    [search]="search.sh|🔍 Search themes"
    [favorite]="favorite.sh|⭐ List or toggle favourites"
    [history]="history.sh|🕐 Theme change history"
    [reset]="reset.sh|♻️  Restore the default theme"
    [validate]="validate.sh|✅ Validate theme files"
    [wcag]="wcag.sh|♿ WCAG contrast of a theme or the catalogue"
    [benchmark]="benchmark.sh|⏱  Measure theme performance"
    [schedule]="schedule.sh|⏰ Schedule theme switching"
    [sync]="sync.sh|☁️  Sync themes to a remote"
    [wallpaper]="wallpaper.sh|🖼  Derive a theme from a wallpaper"
    [ai-generate]="ai-generate.sh|🤖 Generate a theme with AI"
    [ai-mood]="ai-mood.sh|💭 Generate a theme from a mood"
    [ai-time]="ai-time.sh|🕐 Theme for the time of day"
    [ai-weather]="ai-weather.sh|🌤  Theme from current weather"
    [store-browse]="store-browse.sh|🏬 Browse the theme store"
    [store-download]="store-download.sh|⬇️  Download a store theme"
    [store-upload]="store-upload.sh|⬆️  Publish a theme to the store"
)

# Aliases resolve to a canonical subcommand. Kept separate from the table above
# so an alias can never be mistaken for a module with its own file.
declare -gA THEME_ALIASES=(
    [ls]=list  [show]=colors  [info]=colors  [set]=apply  [gen]=create
    [generate]=create  [rm]=delete  [remove]=delete  [rm-theme]=delete
    [favourite]=favorite  [fav]=favorite  [rand]=random  [hist]=history
    [check]=validate  [bench]=benchmark  [sched]=schedule
    [wp]=wallpaper  [ai]=ai-generate  [store]=store-browse  [dl]=store-download
    [ul]=store-upload  [browse]=store-browse  [sync-themes]=sync
)

theme::help() {
    ash_banner "🎨 ASH THEME" "catalogue · generation · contrast · store" "80"

    cat <<EOF

${BOLD}${ASH_PRIMARY}USAGE${RST}
  ${ASH_ACCENT}ash theme${RST} <subcommand> [options]

${BOLD}${ASH_PRIMARY}SUBCOMMANDS${RST}
EOF

    local key desc
    for key in "${!THEME_SUBCOMMANDS[@]}"; do
        desc="${THEME_SUBCOMMANDS[$key]#*|}"
        printf '  %s%-16s%s %s\n' "$ASH_ACCENT" "$key" "$RST" "$desc"
    done | sort

    cat <<EOF

${BOLD}${ASH_PRIMARY}EXAMPLES${RST}
  ${ASH_MUTED}# Browse and preview${RST}
  ash theme list --family nord
  ash theme colors nord
  ash theme preview nord

${ASH_MUTED}# Build config files from a theme, and keep a record${RST}
  ash theme apply nord
  ash theme history --limit 10

${ASH_MUTED}# Derive a theme from a wallpaper or from words${RST}
  ash theme wallpaper ~/Pictures/dusk.jpg --apply
  ash theme ai-generate "deep forest at dusk"
  ash theme ai-mood calm

${ASH_MUTED}# Keep a theme and share it${RST}
  ash theme favorite add nord
  ash theme export nord --format base16 --out ~/nord.yaml

${ASH_MUTED}# Keep it honest${RST}
  ash theme validate --all
  ash theme wcag --sweep
  ash theme reset --undo

${BOLD}${ASH_PRIMARY}CATALOGUE${RST}
  ${ASH_MUTED}Built-in : ${THEME_CATALOGUE_DIR}${RST}
  ${ASH_MUTED}User     : ${THEME_USER_DIR}${RST}
  ${ASH_MUTED}Templates: ${THEME_TEMPLATE_DIR}${RST}

EOF
}

# Load a subcommand module by registry key. Returns non-zero, with a message,
# if the module or its function is missing.
#
# Sourced on demand: `ash theme list` should not have to parse the AI and store
# modules. Submodules are libraries, so they define rather than execute.
theme::source_sub() {
    local sub="$1"
    local entry="${THEME_SUBCOMMANDS[$sub]:-}"

    if [[ -z "$entry" ]]; then
        ash_log_error "Unknown subcommand: ${sub}"
        return 1
    fi

    local file="${_THEME_CMD_DIR}/${entry%%|*}"
    if [[ ! -r "$file" ]]; then
        ash_log_error "Subcommand module missing: $(basename "$file")"
        return 1
    fi

    # Already loaded? Then this is a repeat call, not a second definition.
    local fn="theme::${sub//-/_}"
    if declare -F "$fn" >/dev/null 2>&1; then
        return 0
    fi

    # shellcheck source=/dev/null
    source "$file"

    declare -F "$fn" >/dev/null 2>&1 || {
        ash_log_error "Subcommand function not defined: ${fn}"
        return 1
    }
}

theme::main() {
    local sub="${1:-}"; shift || true

    # Resolve aliases before the empty check: `ash theme t` should reach the
    # list, and an unknown word should say so rather than print the help.
    if [[ -n "$sub" && -n "${THEME_ALIASES[$sub]:-}" ]]; then
        sub="${THEME_ALIASES[$sub]}"
    fi

    case "$sub" in
        ""|help|--help|-h) theme::help; return 0 ;;
    esac

    local entry="${THEME_SUBCOMMANDS[$sub]:-}"
    if [[ -z "$entry" ]]; then
        ash_log_error "Unknown subcommand: ${sub}"
        ash_log_info  "Run 'ash theme --help' for the subcommand list"
        return 1
    fi

    theme::source_sub "$sub" || return 1

    local fn="theme::${sub//-/_}"
    if ! declare -F "$fn" >/dev/null 2>&1; then
        ash_log_error "Subcommand function not defined: ${fn}"
        return 1
    fi

    "$fn" "$@"
}

# Executing this file directly still works; sourcing it — which is how the
# dispatcher loads it — must only define the entry point.
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    theme::main "$@"
fi

ash_cmd_theme() {
    theme::main "$@"
}

# Top-level `ash wcag` entry point — see the ASH_COMMANDS table in ash-cli/ash.
# Only the contrast gate is exposed this way; the rest of the engine is reached
# through `ash theme`.
ash_cmd_wcag() {
    # `ash wcag` is the same code path as `ash theme wcag`, so load the module
    # the same way rather than assuming theme::main has already done it.
    theme::source_sub wcag || return 1
    theme::wcag "$@"
}
