binds {
##################################################
# PASS THROUGH #
##################################################
pass_mouse_when_bound = false
##################################################
# SCROLL BEHAVIOR #
##################################################
scroll_event_delay = 300
##################################################
# WORKSPACE BEHAVIOR #
##################################################
workspace_back_and_forth = true
allow_workspace_cycles = true
workspace_center_on = 1
##################################################
# FOCUS BEHAVIOR #
##################################################
focus_preferred_method = 0
movefocus_cycles_fullscreen = false
##################################################
# WINDOW DIRECTION FALLBACK #
##################################################
window_direction_monitor_fallback = true
##################################################
# DRAG THRESHOLD #
##################################################
drag_threshold = 10
##################################################
# KEYBIND GRABBING #
##################################################
disable_keybind_grabbing = false
##################################################
# HIDE CURSOR #
##################################################
hide_cursor_on_key_press = false

}