binds {
pass_mouse_when_bound = false
scroll_event_delay = 300
workspace_back_and_forth = true
allow_workspace_cycles = true
workspace_center_on = 1
focus_preferred_method = 0
movefocus_cycles_fullscreen = false
window_direction_monitor_fallback = true
drag_threshold = 10
disable_keybind_grabbing = false
}