cursor {
no_hardware_cursors = false
inactive_timeout = 5
no_warps = false
enable_hyprcursor = true
hide_on_key_press = false
hide_on_touch = true
zoom_factor = 1.0
zoom_rigid = false
}
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Bibata-Modern-Ice
env = HYPRCURSOR_SIZE,24