# ASH completion for bash — generated by ash completion bash
# Source this in ~/.bashrc or place in /etc/bash_completion.d/
_ash_completions() {
    local cur prev words cword
    _init_completion || return
    local commands="theme mode plugin snapshot config doctor hw net update shot wallpaper bar power monitor audio bluetooth window workspace gaming backup analytics profile cloud store session ai macro remote benchmark migrate wcag help version"
    local subcommands=""
    case "${words[1]}" in
        theme) subcommands="list apply create delete edit export favorite history import pick preview random reset schedule search store-browse store-download store-upload sync validate wcag colors clone benchmark" ;;
        mode) subcommands="game work focus cinema present battery stream privacy accessibility default create list status" ;;
        plugin) subcommands="list install remove enable disable search info browse create publish update validate" ;;
        snapshot) subcommands="create restore list delete diff export" ;;
        *) subcommands="" ;;
    esac
    if [[ $cword -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "$commands" -- "$cur") )
    elif [[ $cword -eq 2 && -n "$subcommands" ]]; then
        COMPREPLY=( $(compgen -W "$subcommands" -- "$cur") )
    fi
}
complete -F _ash_completions ash
