# ╔═══════════════════════════════════════════════════════════════════════════════╗
# ║           ASH DOTFILES v3.0 — QT6CT COLOR SCHEME (ASH DARK)               ║
# ╚═══════════════════════════════════════════════════════════════════════════════╝

[ColorScheme]
active_colors       = #ffcdd6f4, #ff1e1e2e, #ff45475a, #ff585b70, #ff181825, #ff11111b, #ffcdd6f4, #ffcdd6f4, #ffcdd6f4, #ff1e1e2e, #ff313244, #ff6c7086, #ffcba6f7, #ff1e1e2e, #ffcba6f7, #fff38ba8, #ffa6e3a1, #ffe0e0e0, #ffcdd6f4, #ff313244, #ff585b70

inactive_colors     = #ffbac2de, #ff1e1e2e, #ff45475a, #ff585b70, #ff181825, #ff11111b, #ffbac2de, #ffbac2de, #ffbac2de, #ff1e1e2e, #ff313244, #ff6c7086, #ff89b4fa, #ff1e1e2e, #ff89b4fa, #fff38ba8, #ffa6e3a1, #ffe0e0e0, #ffbac2de, #ff313244, #ff45475a

disabled_colors     = #ff7f849c, #ff1e1e2e, #ff313244, #ff45475a, #ff181825, #ff11111b, #ff7f849c, #ff7f849c, #ff7f849c, #ff1e1e2e, #ff313244, #ff6c7086, #ff7f849c, #ff1e1e2e, #ff7f849c, #fff38ba8, #ffa6e3a1, #ffe0e0e0, #ff7f849c, #ff313244, #ff45475a