#!/usr/bin/env bash
# ╔══════════════════════════════════════════════════════════════════════════════════════╗
# ║  ASH DOTFILES v5.0 OMEGA ◆ CONFIG EXPORT                                          ║
# ║  Export configuration as JSON, TOML, ENV, or encrypted archive                   ║
# ╚══════════════════════════════════════════════════════════════════════════════════════╝
set -euo pipefail

config::export::help() {
    cat <<EOF
${BOLD}${ASH_PRIMARY}USAGE${RST}
  ash config export [options]

${BOLD}${ASH_PRIMARY}OPTIONS${RST}
  ${ASH_MUTED}--format,  -F FORMAT${RST}   Output format: json|toml|env|conf (default: json)
  ${ASH_MUTED}--output,  -o PATH${RST}     Write to file (default: stdout)
  ${ASH_MUTED}--section, -s SECTION${RST}  Export only this section
  ${ASH_MUTED}--modified-only${RST}        Export only keys that differ from defaults
  ${ASH_MUTED}--encrypt, -e${RST}          Encrypt output with GPG symmetric cipher
  ${ASH_MUTED}--gpg-key KEY${RST}          GPG recipient key for asymmetric encryption
  ${ASH_MUTED}--include-defaults${RST}     Include keys at their default values
  ${ASH_MUTED}--pretty${RST}               Pretty-print output (where applicable)
  ${ASH_MUTED}--help,    -h${RST}           Show this help

${BOLD}${ASH_PRIMARY}FORMATS${RST}
  ${ASH_ACCENT}json${RST}   Machine-readable JSON object, nested by section
  ${ASH_ACCENT}toml${RST}   TOML format with section headers
  ${ASH_ACCENT}env${RST}    Shell-sourceable KEY=VALUE pairs (ASH_ prefixed)
  ${ASH_ACCENT}conf${RST}   Native ash.conf format (default format)

${BOLD}${ASH_PRIMARY}EXAMPLES${RST}
  ash config export
  ash config export --format toml --output ~/ash-config.toml
  ash config export --format env --section theme
  ash config export --encrypt --output ~/ash-config.json.gpg
  ash config export --modified-only --format json
EOF
}

# ── Convert flat key=val map to nested JSON ───────────────────────────────────
_export::to_nested_json() {
    local -n _kv_map="$1"  # nameref: associative array key->value
    local result="{}"
    for key in "${!_kv_map[@]}"; do
        local value="${_kv_map[${key}]}"
        # Build nested path: a.b.c → {"a":{"b":{"c":"value"}}}
        result=$(printf '%s' "${result}" | \
            python3 -c "
import json,sys
data=json.load(sys.stdin)
parts='${key}'.split('.')
d=data
for p in parts[:-1]:
    d=d.setdefault(p,{})
val='${value}'
# Type coerce
if val.lower() in ('true','false'):
    d[parts[-1]]=(val.lower()=='true')
elif val.lstrip('-').isdigit():
    d[parts[-1]]=int(val)
else:
    try:
        d[parts[-1]]=float(val)
    except:
        d[parts[-1]]=val
print(json.dumps(data))
" 2>/dev/null || printf '%s' "${result}")
    done
    printf '%s' "${result}"
}

# ── TOML renderer ─────────────────────────────────────────────────────────────
_export::to_toml() {
    local -n _kv="$1"
    local prev_section=""
    for key in $(printf '%s\n' "${!_kv[@]}" | sort); do
        local value="${_kv[${key}]}"
        local section; section=$(printf '%s' "${key}" | cut -d. -f1)
        local sub_key; sub_key=$(printf '%s' "${key}" | cut -d. -f2-)

        if [[ "${section}" != "${prev_section}" ]]; then
            printf '\n[%s]\n' "${section}"
            prev_section="${section}"
        fi

        # TOML typing
        local type; type=$(cfg::_schema_type "${key}" 2>/dev/null || printf "string")
        case "${type}" in
            boolean|integer|float)
                printf '%s = %s\n' "${sub_key}" "${value}"
                ;;
            *)
                printf '%s = "%s"\n' "${sub_key}" "${value}"
                ;;
        esac
    done
}

# ── ENV renderer ──────────────────────────────────────────────────────────────
_export::to_env() {
    local -n _kv="$1"
    for key in $(printf '%s\n' "${!_kv[@]}" | sort); do
        local value="${_kv[${key}]}"
        local env_key
        env_key=$(printf '%s' "ASH_${key}" | tr '.' '_' | tr '[:lower:]' '[:upper:]')
        printf 'export %s=%q\n' "${env_key}" "${value}"
    done
}

# ── CONF renderer (native format) ─────────────────────────────────────────────
_export::to_conf() {
    local -n _kv="$1"
    printf '# ASH Configuration Export — %s\n' "$(date '+%Y-%m-%d %H:%M:%S')"
    printf '# Generated by: ash config export\n\n'
    local prev_section=""
    for key in $(printf '%s\n' "${!_kv[@]}" | sort); do
        local value="${_kv[${key}]}"
        local section; section=$(printf '%s' "${key}" | cut -d. -f1)
        if [[ "${section}" != "${prev_section}" ]]; then
            printf '\n# ── %s ──\n' "${section}"
            prev_section="${section}"
        fi
        printf '%-45s = %s\n' "${key}" "${value}"
    done
}

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
config::export() {
    local format="json" output="" section_filter="" modified_only=false
    local encrypt=false gpg_key="" include_defaults=false pretty=false

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --help|-h)           config::export::help; return 0 ;;
            --format|-F)         format="${2:?'--format requires FORMAT'}"; shift 2 ;;
            --output|-o)         output="${2:?'--output requires PATH'}"; shift 2 ;;
            --section|-s)        section_filter="${2:?'--section requires SECTION'}"; shift 2 ;;
            --modified-only)     modified_only=true; shift ;;
            --encrypt|-e)        encrypt=true; shift ;;
            --gpg-key)           gpg_key="${2:?'--gpg-key requires KEY'}"; shift 2 ;;
            --include-defaults)  include_defaults=true; shift ;;
            --pretty)            pretty=true; shift ;;
            -*)                  log::error "Unknown option: $1"; return 1 ;;
            *)                   shift ;;
        esac
    done

    local file="${CFG_ACTIVE_FILE:-${CFG_MAIN_FILE}}"

    # ── Collect key-value pairs ────────────────────────────────────────────────
    declare -A kv_map

    for schema_line in "${CFG_SCHEMA[@]}"; do
        IFS='|' read -ra parts <<< "${schema_line}"
        local key="${parts[0]}" default_val="${parts[2]}"
        local section; section=$(printf '%s' "${key}" | cut -d. -f1)

        [[ -n "${section_filter}" ]] && [[ "${section}" != "${section_filter}" ]] && continue

        local current; current=$(cfg::_read_raw "${key}" "${file}")
        local effective="${current:-${default_val}}"

        if [[ "${modified_only}" == "true" ]]; then
            [[ -z "${current}" ]] && continue
            [[ "${current}" == "${default_val}" ]] && continue
        fi

        [[ -z "${effective}" ]] && [[ "${include_defaults}" == "false" ]] && continue
        [[ -n "${effective}" ]] && kv_map["${key}"]="${effective}"
    done

    # ── Render ────────────────────────────────────────────────────────────────
    local rendered=""
    case "${format,,}" in
        json)
            if command -v python3 &>/dev/null; then
                rendered=$(_export::to_nested_json kv_map)
                [[ "${pretty}" == "true" ]] && \
                    rendered=$(printf '%s' "${rendered}" | python3 -m json.tool 2>/dev/null)
            else
                # Flat JSON fallback
                rendered='{'
                local first=true
                for key in $(printf '%s\n' "${!kv_map[@]}" | sort); do
                    [[ "${first}" == "true" ]] && first=false || rendered+=','
                    rendered+=$(printf '"%s":"%s"' "${key}" "${kv_map[${key}]}")
                done
                rendered+='}'
            fi
            ;;
        toml)
            rendered=$(_export::to_toml kv_map)
            ;;
        env)
            rendered=$(_export::to_env kv_map)
            ;;
        conf)
            rendered=$(_export::to_conf kv_map)
            ;;
        *)
            log::error "Unknown format: '${format}'"
            log::info  "Supported: json toml env conf"
            return 1
            ;;
    esac

    # ── Encrypt ───────────────────────────────────────────────────────────────
    if [[ "${encrypt}" == "true" ]] || [[ -n "${gpg_key}" ]]; then
        utils::require "gpg"
        local tmp_plain; tmp_plain=$(mktemp)
        printf '%s\n' "${rendered}" > "${tmp_plain}"

        local tmp_enc; tmp_enc=$(mktemp)

        if [[ -n "${gpg_key}" ]]; then
            gpg --batch --yes -r "${gpg_key}" -e \
                --output "${tmp_enc}" "${tmp_plain}" 2>/dev/null
        else
            printf '\n  %sEncryption passphrase: %s' "${ASH_PRIMARY}" "${RST}" >&2
            local pass; read -rs pass; printf '\n' >&2
            printf '\n  %sConfirm passphrase:    %s' "${ASH_PRIMARY}" "${RST}" >&2
            local pass2; read -rs pass2; printf '\n' >&2
            [[ "${pass}" != "${pass2}" ]] && {
                log::error "Passphrases do not match"
                rm -f "${tmp_plain}" "${tmp_enc}"
                return 1
            }
            printf '%s' "${pass}" | \
                gpg --batch --yes --symmetric --cipher-algo AES256 \
                    --passphrase-fd 0 --output "${tmp_enc}" "${tmp_plain}" 2>/dev/null
        fi
        rm -f "${tmp_plain}"

        if [[ -n "${output}" ]]; then
            mv "${tmp_enc}" "${output}"
            log::success "Encrypted config exported to: ${output}" >&2
        else
            cat "${tmp_enc}"
            rm -f "${tmp_enc}"
        fi
        return 0
    fi

    # ── Write/print ───────────────────────────────────────────────────────────
    if [[ -n "${output}" ]]; then
        mkdir -p "$(dirname "${output}")"
        printf '%s\n' "${rendered}" > "${output}"
        local size; size=$(du -sh "${output}" 2>/dev/null | awk '{print $1}')
        local kcount="${#kv_map[@]}"
        log::blank >&2
        log::success "Config exported" >&2
        printf '  %s%-12s%s %s%s%s\n' \
            "${ASH_MUTED}" "File"   "${RST}" "${ASH_ACCENT}"      "${output}"  "${RST}" >&2
        printf '  %s%-12s%s %s%s%s\n' \
            "${ASH_MUTED}" "Format" "${RST}" "${SNAP_COLOR_NAME}" "${format}"  "${RST}" >&2
        printf '  %s%-12s%s %s%d keys%s\n' \
            "${ASH_MUTED}" "Keys"   "${RST}" "${SNAP_COLOR_SIZE}" "${kcount}"  "${RST}" >&2
        printf '  %s%-12s%s %s%s%s\n' \
            "${ASH_MUTED}" "Size"   "${RST}" "${SNAP_COLOR_SIZE}" "${size}"    "${RST}" >&2
        log::blank >&2
    else
        printf '%s\n' "${rendered}"
    fi
}
