-- ╔══════════════════════════════════════════════════════════════════════════════╗
-- ║  ASH DOTFILES v5.0 OMEGA — WEZTERM THEME: ASH DYNAMIC                    ║
-- ║                                                                            ║
-- ║  Auto-generated by ASH Theme Engine                                        ║
-- ║  Source: ~/.config/ash/state/current-theme.json                           ║
-- ║  Template: ash-cli/engines/color-engine/templates/wezterm.template        ║
-- ║                                                                            ║
-- ║  ⚡ This file is AUTOMATICALLY MANAGED by ASH.                            ║
-- ║  ⚡ Manual edits will be OVERWRITTEN on next theme change.                ║
-- ║                                                                            ║
-- ║  Generation: {{TIMESTAMP}}                                                 ║
-- ║  Active theme: {{THEME_NAME}}                                              ║
-- ║  Variant: {{THEME_VARIANT}} (dark|light|neon|nature|etc)                  ║
-- ║  Wallpaper dominant: {{WALLPAPER_DOMINANT}}                               ║
-- ╚══════════════════════════════════════════════════════════════════════════╝

local M = {}

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--  APPLY FUNCTION — Called from wezterm.lua
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

--- Apply the ASH dynamic color scheme to WezTerm config
--- @param config table   WezTerm config builder object
--- @param palette table  Catppuccin color palette from wezterm.lua
function M.apply(config, palette)

    -- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    --  🎨  COLOR SCHEME — Full terminal color mapping
    --  ASH tokens: {{COLOR_*}} replaced by engine
    -- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    config.color_scheme = "ash-dynamic-generated"

    -- Define the color scheme inline
    -- (WezTerm supports inline color scheme definitions since 20230320)
    local wezterm = require "wezterm"

    wezterm.add_to_config_errors = false

    config.colors = {

        -- ── ANSI Standard Colors ───────────────────────────────────────────
        --
        -- Map to Catppuccin Mocha semantic colors:
        -- The 8 ANSI colors (0-7) and their bright variants (8-15)
        -- These affect all terminal programs that use ANSI colors

        ansi = {
            -- 0: Black  → Catppuccin Surface1 (visible on dark bg)
            palette.surface1,
            -- 1: Red    → Catppuccin Red
            palette.red,
            -- 2: Green  → Catppuccin Green
            palette.green,
            -- 3: Yellow → Catppuccin Yellow
            palette.yellow,
            -- 4: Blue   → Catppuccin Blue
            palette.blue,
            -- 5: Magenta → Catppuccin Mauve (primary accent)
            palette.mauve,
            -- 6: Cyan   → Catppuccin Teal
            palette.teal,
            -- 7: White  → Catppuccin Subtext1 (dimmer than text)
            palette.subtext1,
        },

        brights = {
            -- 8:  Bright Black  → Catppuccin Overlay0 (used for comments)
            palette.overlay0,
            -- 9:  Bright Red    → Catppuccin Maroon (softer danger)
            palette.maroon,
            -- 10: Bright Green  → Catppuccin Teal (lighter success)
            palette.teal,
            -- 11: Bright Yellow → Catppuccin Peach (warm highlight)
            palette.peach,
            -- 12: Bright Blue   → Catppuccin Lavender (soft blue)
            palette.lavender,
            -- 13: Bright Magenta → Catppuccin Pink (highlight accent)
            palette.pink,
            -- 14: Bright Cyan   → Catppuccin Sky (bright info)
            palette.sky,
            -- 15: Bright White  → Catppuccin Text (full brightness)
            palette.text,
        },

        -- ── Extended Colors (256-color palette) ───────────────────────────
        -- WezTerm uses these for 256-color terminal programs

        -- ── UI Colors ─────────────────────────────────────────────────────

        -- Background — Catppuccin Base
        -- ASH token: {{COLOR_BASE}}
        background = palette.base,

        -- Foreground — Catppuccin Text
        -- ASH token: {{COLOR_TEXT}}
        foreground = palette.text,

        -- ── Cursor ────────────────────────────────────────────────────────

        cursor_bg       = palette.mauve,   -- Cursor fill — Mauve accent
        cursor_fg       = palette.base,    -- Text under cursor — Base (inverted)
        cursor_border   = palette.mauve,   -- Cursor border — matches fill

        -- ── Selection ─────────────────────────────────────────────────────

        selection_fg    = palette.text,    -- Selected text color
        selection_bg    = palette.surface1, -- Selection background — Surface1

        -- ── Split / Pane Dividers ─────────────────────────────────────────

        split           = palette.surface0, -- Pane split line color

        -- ── Scrollbar ─────────────────────────────────────────────────────

        scrollbar_thumb = palette.surface2,  -- Scrollbar handle

        -- ── Copy Mode ─────────────────────────────────────────────────────

        copy_mode_active_highlight_bg   = { AnsiColor = "Black" },
        copy_mode_active_highlight_fg   = { AnsiColor = "BrightBlue" },
        copy_mode_inactive_highlight_bg = { Color = palette.surface0 },
        copy_mode_inactive_highlight_fg = { Color = palette.text },

        -- ── Quick Select ──────────────────────────────────────────────────

        quick_select_label_bg   = { Color = palette.mauve  },
        quick_select_label_fg   = { Color = palette.base   },
        quick_select_match_bg   = { AnsiColor = "Navy"     },
        quick_select_match_fg   = { Color = palette.text   },

        -- ── Tab Bar ───────────────────────────────────────────────────────

        tab_bar = {
            background         = palette.mantle,

            -- Active tab
            active_tab = {
                bg_color    = palette.mauve,
                fg_color    = palette.base,
                intensity   = "Bold",
                underline   = "None",
                italic      = false,
                strikethrough = false,
            },

            -- Inactive tabs
            inactive_tab = {
                bg_color    = palette.surface0,
                fg_color    = palette.overlay1,
                intensity   = "Normal",
            },

            -- Inactive tab on hover
            inactive_tab_hover = {
                bg_color    = palette.surface1,
                fg_color    = palette.subtext1,
                italic      = false,
            },

            -- New tab (+) button
            new_tab = {
                bg_color    = palette.surface0,
                fg_color    = palette.overlay1,
            },

            new_tab_hover = {
                bg_color    = palette.surface1,
                fg_color    = palette.text,
                italic      = false,
            },

            -- Edge between inactive tabs
            inactive_tab_edge       = palette.mantle,
            inactive_tab_edge_hover = palette.surface1,
        },

        -- ── Indexed Color Overrides ───────────────────────────────────────
        -- Override specific 256-color palette indices
        -- Used by terminal programs requesting specific palette entries

        indexed = {
            -- 16: Extra orange (between ANSI yellow and red)
            [16] = palette.peach,
            -- 17: Extra dark red
            [17] = palette.maroon,
        },
    }

    -- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    --  🌟  VISUAL BELL — Flash color on terminal bell
    -- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    config.visual_bell = {
        fade_in_function    = "EaseIn",
        fade_in_duration_ms  = 100,
        fade_out_function   = "EaseOut",
        fade_out_duration_ms = 250,
        target              = "BackgroundColor",
    }

    -- Visual bell color (flashes briefly on bell)
    -- Uses peach for a warm, non-alarming flash
    config.colors.visual_bell = palette.surface1

    -- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    --  🔗  HYPERLINK STYLE
    -- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    -- Hyperlink hover style
    config.colors.compose_cursor = palette.lavender

    -- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    --  🎭  SEMANTIC ZONES — Highlight zones in terminal output
    -- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    -- Semantic zone colors (used by shell integration)
    -- These highlight command output zones with subtle background colors
    config.use_cap_height_to_scale_fallback_fonts = true

    -- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    --  📐  WINDOW BACKGROUND — Gradient/image support
    -- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    -- Option A: Solid color background (current default)
    -- background is set via config.colors.background above

    -- Option B: Subtle gradient background
    -- (uncomment to enable)
    --[[
    config.window_background_gradient = {
        orientation = "Vertical",
        colors = {
            palette.crust,   -- Top: deepest
            palette.base,    -- Bottom: normal
        },
        blend = "LinearRgb",
        noise = 64,          -- Subtle film grain
    }
    ]]

    -- Option C: Wallpaper background (with blur via Hyprland)
    -- (uncomment to enable — requires Hyprland window blur rule)
    --[[
    local wallpaper = os.getenv("ASH_WALLPAPER")
    if wallpaper then
        config.window_background_image = wallpaper
        config.window_background_image_hsb = {
            brightness = 0.08,  -- Very dim for readability
            hue = 1.0,
            saturation = 0.8,
        }
    end
    ]]

    -- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    --  🎨  THEME-VARIANT SPECIFIC OVERRIDES
    --  ASH engine sets THEME_VARIANT env variable
    -- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    local variant = os.getenv("ASH_THEME_VARIANT") or "dark"

    if variant == "light" then
        -- Light variant: swap some colors for better contrast
        config.colors.background        = "#eff1f5"  -- Catppuccin Latte Base
        config.colors.foreground        = "#4c4f69"  -- Catppuccin Latte Text
        config.colors.cursor_bg         = "#8839ef"  -- Catppuccin Latte Mauve
        config.colors.cursor_fg         = "#eff1f5"
        config.colors.selection_bg      = "#ccd0da"  -- Catppuccin Latte Surface0
        config.colors.tab_bar.background = "#e6e9ef"  -- Catppuccin Latte Mantle

    elseif variant == "neon" then
        -- Neon variant: high saturation accents, pitch black bg
        config.colors.background        = "#000000"
        config.colors.cursor_bg         = "#ff00ff"
        config.colors.selection_bg      = "#1a0030"

    elseif variant == "minimal" then
        -- Minimal: near-monochrome, very subtle
        config.window_background_opacity = 0.98
    end

end

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--  📊  THEME METADATA — Used by ASH for tracking
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

M.metadata = {
    name      = "ASH Dynamic",
    version   = "5.0.0",
    generated = "{{TIMESTAMP}}",
    theme     = "{{THEME_NAME}}",
    variant   = "{{THEME_VARIANT}}",
    checksum  = "{{CHECKSUM}}",
}

return M