layerrule = animation slide top, waybar
layerrule = animation popin 80%, rofi
layerrule = animation slide right, notifications
layerrule = animation slide right, dunst
layerrule = animation slide right, swaync
