workspace = 1, name:web, persistent:true, gapsout:12, default:true
workspace = 2, name:code, persistent:true, gapsout:12
workspace = 3, name:term, persistent:true, gapsout:8
workspace = 4, name:chat, persistent:true, gapsout:12
workspace = 5, name:media, gapsout:0, gapsin:0
workspace = 6, name:files, gapsout:12
workspace = 7, name:gfx, gapsout:0, gapsin:0
workspace = 8, name:games, gapsout:0, gapsin:0
workspace = 9, name:vm, gapsout:12
workspace = 10, name:misc, gapsout:12
workspace = special:magic, \
on-created-empty:kitty, gapsout:60
workspace = special:scratch, \
on-created-empty:kitty --class scratchnotes -e nvim ~/scratch.md, \
gapsout:80