# ╔═══════════════════════════════════════════════════════════════════════════════╗
# ║           ASH DOTFILES v3.0 — FISH PROMPT CONFIGURATION                    ║
# ║           Loaded last — configures prompt and final settings               ║
# ╚═══════════════════════════════════════════════════════════════════════════════╝

# ═══════════════════════════════════════════════════════════════════════════════
# 🎨 SYNTAX HIGHLIGHTING COLORS
# ═══════════════════════════════════════════════════════════════════════════════

# These are the base colors — overridden by themes/current.fish
# which is generated by the ASH theme engine

if not test -f ~/.config/fish/themes/current.fish
    # Default Catppuccin Mocha colors (fallback)
    set -g fish_color_normal           cdd6f4
    set -g fish_color_command          cba6f7
    set -g fish_color_keyword          cba6f7
    set -g fish_color_quote            a6e3a1
    set -g fish_color_redirection      94e2d5
    set -g fish_color_end              cdd6f4
    set -g fish_color_error            f38ba8
    set -g fish_color_param            bac2de
    set -g fish_color_comment          6c7086
    set -g fish_color_selection        --background=313244
    set -g fish_color_search_match     --background=313244
    set -g fish_color_operator         89b4fa
    set -g fish_color_escape           94e2d5
    set -g fish_color_autosuggestion   7f849c
    set -g fish_color_cancel           f38ba8
    set -g fish_color_cwd              89b4fa
    set -g fish_color_user             cba6f7
    set -g fish_color_host             89b4fa
    set -g fish_color_status           f38ba8
    set -g fish_pager_color_prefix     cba6f7
    set -g fish_pager_color_completion cdd6f4
    set -g fish_pager_color_description 7f849c
    set -g fish_pager_color_progress   7f849c
    set -g fish_pager_color_selected_background --background=313244
end

# ═══════════════════════════════════════════════════════════════════════════════
# ⚡ STARSHIP INIT
# ═══════════════════════════════════════════════════════════════════════════════

# Initialize starship if available
if command -q starship
    starship init fish | source
end

# ═══════════════════════════════════════════════════════════════════════════════
# 🔧 ZOXIDE INIT
# ═══════════════════════════════════════════════════════════════════════════════

if command -q zoxide
    zoxide init fish | source
end

# ═══════════════════════════════════════════════════════════════════════════════
# 📊 ATUIN INIT (optional — shell history sync)
# ═══════════════════════════════════════════════════════════════════════════════

if command -q atuin
    atuin init fish --disable-up-arrow | source
end

# ═══════════════════════════════════════════════════════════════════════════════
# 🐟 FISH SETTINGS
# ═══════════════════════════════════════════════════════════════════════════════

# Disable greeting (handled by fish_greeting.fish)
set -g fish_greeting ""

# Tab completion behavior
set -g fish_complete_path $fish_complete_path ~/.config/fish/completions

# History
set -g fish_history_max 10000

# Pager colors (set after sourcing theme to override if needed)
set -g fish_pager_color_progress     (set_color --bold brblack)
set -g fish_pager_color_background   (set_color normal)

# ═══════════════════════════════════════════════════════════════════════════════
# 🔔 STARTUP NOTIFICATION
# ═══════════════════════════════════════════════════════════════════════════════

# Show current wallpaper info in greeting context
function __ash_check_wallpaper
    set -l wallpaper_file ~/.cache/ash-dots/wallpaper/last
    if test -f $wallpaper_file
        set -g ASH_CURRENT_WALLPAPER (cat $wallpaper_file)
    end
end

__ash_check_wallpaper