#!/bin/bash
set -euo pipefail
# ╔═══════════════════════════════════════════════════════════════════════════════╗
# ║           ASH DOTFILES v3.0 — GENERATE ALL PLACEHOLDER FILES               ║
# ║           Creates placeholder files for generated content                  ║
# ╚═══════════════════════════════════════════════════════════════════════════════╝

set -euo pipefail

readonly CONFIG_DIR="${HOME}/.config"
readonly CACHE_DIR="${HOME}/.cache/ash-dots"
readonly LOG_FILE="${CACHE_DIR}/logs/generate.log"

log()  { echo "$(date '+%Y-%m-%d %H:%M:%S') $*" >> "${LOG_FILE}" 2>/dev/null || true; }
info() { echo -e "  \033[96m→\033[0m $*"; log "INFO" "$*"; }
ok()   { echo -e "  \033[92m✓\033[0m $*"; log "OK" "$*"; }

mkdir -p "${CACHE_DIR}/logs"

echo ""
echo "  🔧 Generating placeholder files for ASH Dotfiles..."
echo ""

# ── Hyprland active theme ─────────────────────────────────────────────────────
if [[ ! -f "${CONFIG_DIR}/hypr/themes/active.conf" ]]; then
    mkdir -p "${CONFIG_DIR}/hypr/themes"
    cat > "${CONFIG_DIR}/hypr/themes/active.conf" << 'EOF'
# ASH Theme Engine — Active Theme (placeholder)
# This file is auto-generated by theme-engine.sh
# Run: ash theme pick

general {
    col.active_border   = rgba(cba6f7ff) rgba(89b4faff) rgba(94e2d5ff) 60deg
    col.inactive_border = rgba(313244aa)
}
EOF
    ok "Created: hypr/themes/active.conf"
fi

# ── Kitty current theme ───────────────────────────────────────────────────────
if [[ ! -f "${CONFIG_DIR}/kitty/themes/current.conf" ]]; then
    mkdir -p "${CONFIG_DIR}/kitty/themes"
    cat > "${CONFIG_DIR}/kitty/themes/current.conf" << 'EOF'
# ASH Theme Engine — Kitty Theme (placeholder)
# Auto-generated by theme-engine.sh
background  #1e1e2e
foreground  #cdd6f4
cursor      #cba6f7
EOF
    ok "Created: kitty/themes/current.conf"
fi

# ── Waybar colors CSS ─────────────────────────────────────────────────────────
if [[ ! -f "${CONFIG_DIR}/waybar/styles/colors.css" ]]; then
    mkdir -p "${CONFIG_DIR}/waybar/styles"
    cat > "${CONFIG_DIR}/waybar/styles/colors.css" << 'EOF'
/* ASH Theme Engine — Waybar Colors (placeholder) */
@define-color base       #1e1e2e;
@define-color primary    #cba6f7;
@define-color secondary  #89b4fa;
@define-color text       #cdd6f4;
@define-color success    #a6e3a1;
@define-color warning    #f9e2af;
@define-color error      #f38ba8;
EOF
    ok "Created: waybar/styles/colors.css"
fi

# ── Rofi dynamic theme ────────────────────────────────────────────────────────
if [[ ! -f "${CONFIG_DIR}/rofi/themes/ash-dynamic.rasi" ]]; then
    mkdir -p "${CONFIG_DIR}/rofi/themes"
    cat > "${CONFIG_DIR}/rofi/themes/ash-dynamic.rasi" << 'EOF'
/* ASH Theme Engine — Rofi Dynamic Theme (placeholder) */
* {
    background-color: #1e1e2eee;
    text-color: #cdd6f4;
    font: "JetBrainsMono Nerd Font 12";
}
window {
    border: 2px solid #cba6f7;
    border-radius: 14px;
    padding: 16px;
    width: 640px;
}
inputbar {
    background-color: #313244;
    border-radius: 10px;
    padding: 8px 12px;
}
element selected {
    background-color: #313244;
    color: #cba6f7;
    border-radius: 8px;
}
EOF
    ok "Created: rofi/themes/ash-dynamic.rasi"
fi

# ── Fish colors theme ─────────────────────────────────────────────────────────
if [[ ! -f "${CONFIG_DIR}/fish/themes/current.fish" ]]; then
    mkdir -p "${CONFIG_DIR}/fish/themes"
    cat > "${CONFIG_DIR}/fish/themes/current.fish" << 'EOF'
# ASH Theme Engine — Fish Colors (placeholder)
set -g fish_color_normal           cdd6f4
set -g fish_color_command          cba6f7
set -g fish_color_quote            a6e3a1
set -g fish_color_error            f38ba8
set -g fish_color_autosuggestion   7f849c
EOF
    ok "Created: fish/themes/current.fish"
fi

# ── Dunstrc ───────────────────────────────────────────────────────────────────
if [[ ! -f "${CONFIG_DIR}/dunst/dunstrc" ]]; then
    info "dunstrc missing — will be generated by theme-engine.sh"
fi

# ── Cache directories ─────────────────────────────────────────────────────────
mkdir -p "${CACHE_DIR}/colors"
mkdir -p "${CACHE_DIR}/wallpaper"
mkdir -p "${CACHE_DIR}/logs"

# Generate fallback color cache
if [[ ! -f "${CACHE_DIR}/colors/current.json" ]]; then
    cat > "${CACHE_DIR}/colors/current.json" << 'EOF'
{
    "_meta": {
        "generated": "placeholder",
        "version": "3.0.0",
        "generator": "generate-all.sh"
    },
    "backgrounds": {
        "base": "#1e1e2e",
        "mantle": "#181825",
        "crust": "#11111b"
    },
    "accents": {
        "primary": "#cba6f7",
        "secondary": "#89b4fa",
        "tertiary": "#94e2d5"
    },
    "text": {
        "text": "#cdd6f4",
        "subtext1": "#bac2de"
    },
    "states": {
        "success": "#a6e3a1",
        "warning": "#f9e2af",
        "error": "#f38ba8",
        "info": "#89b4fa"
    }
}
EOF
    ok "Created: color cache placeholder"
fi

echo ""
ok "All placeholders generated!"
echo ""
info "Run 'ash theme pick' to generate real theme from wallpaper"
echo ""
log "INFO" "generate-all complete"