source = ~/.config/hypr/core/env.conf
source = ~/.config/hypr/core/monitors.conf
source = ~/.config/hypr/core/input.conf
source = ~/.config/hypr/core/general.conf
source = ~/.config/hypr/core/cursor.conf
source = ~/.config/hypr/core/binds.conf
source = ~/.config/hypr/modules/decorations.conf
source = ~/.config/hypr/modules/animations.conf
source = ~/.config/hypr/modules/blur.conf
source = ~/.config/hypr/modules/lighting.conf
source = ~/.config/hypr/modules/misc.conf
source = ~/.config/hypr/modules/layouts.conf
source = ~/.config/hypr/modules/gestures.conf
source = ~/.config/hypr/modules/keybinds.conf
source = ~/.config/hypr/modules/submaps.conf
source = ~/.config/hypr/modules/media-keys.conf
source = ~/.config/hypr/rules/windowrules.conf
source = ~/.config/hypr/rules/workspacerules.conf
source = ~/.config/hypr/rules/layerrules.conf
source = ~/.config/hypr/themes/active.conf
source = ~/.config/hypr/modules/autostart.conf
source = ~/.config/hypr/UserOverrides/user.conf