exec-once = sleep 0.3 &amp;&amp; /usr/lib/xdg-desktop-portal-hyprland &amp;
exec-once = sleep 0.8 &amp;&amp; /usr/lib/xdg-desktop-portal &amp;
exec-once = dbus-update-activation-environment --systemd \
WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE \
HYPRLAND_INSTANCE_SIGNATURE QT_QPA_PLATFORM GDK_BACKEND
exec-once = systemctl --user import-environment \
WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE \
HYPRLAND_INSTANCE_SIGNATURE 2&gt;/dev/null
exec-once = systemctl --user start graphical-session.target 2&gt;/dev/null
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &amp;
exec-once = /usr/lib/gnome-keyring-daemon --start \
--components=pkcs11,secrets,ssh 2&gt;/dev/null &amp;
exec-once = swww-daemon --format xrgb &amp;
exec-once = sleep 1.0 &amp;&amp; \
