decoration {
rounding = 16
rounding_power = 2.0
active_opacity = 1.0
inactive_opacity = 0.86
fullscreen_opacity = 1.0
blur {
enabled = true
size = 12
passes = 4
new_optimizations = true
noise = 0.0095
contrast = 0.8800
brightness = 0.8000
vibrancy = 0.2100
vibrancy_darkness = 0.4000
special = true
popups = true
popups_ignorealpha = 0.18
}
shadow {
enabled = true
range = 40
render_power = 3
color = rgba(7c3aed99)
color_inactive = rgba(0a0a1455)
offset = 6 12
scale = 1.05
}
dim_inactive = true
dim_strength = 0.065
dim_special = 0.40
dim_around = 0.70

}