##################################################
# DWINDLE LAYOUT #
##################################################
dwindle {
pseudotile = false
force_split = 0
preserve_split = true
smart_split = false
smart_resizing = true
permanent_direction_override = false
special_scale_factor = 0.88
split_width_multiplier = 1.0
no_gaps_when_only = 0
use_active_for_splits = true
default_split_ratio = 1.0
}

##################################################
# MASTER LAYOUT #
##################################################
master {
allow_small_split = false
special_scale_factor = 0.80
mfact = 0.55
new_status = slave
new_on_top = false
new_on_active = after
no_gaps_when_only = 0
orientation = left
inherit_fullscreen = true
always_center_master = false
smart_resizing = true
drop_at_cursor = true
}

##################################################
# GROUP SETTINGS #
##################################################
group {
insert_after_current = true
focus_removed_window = true
col.border_active = rgba(7c3aedff) rgba(2563ebff) 45deg
col.border_inactive = rgba(1c1c32ff)
col.border_locked_active = rgba(d97706ff)
col.border_locked_inactive = rgba(44440aff)
groupbar {
enabled = true
font_family = JetBrainsMono Nerd Font
font_size = 10
gradients = true
gradient_rounding = 6
render_titles = true
scrolling = true
text_color = rgba(cdd6f4ff)
col.active = rgba(7c3aed88)
col.inactive = rgba(1c1c3288)
col.locked_active = rgba(d9770688)
col.locked_inactive = rgba(44440a88)
height = 22
stacked = false
priority = 3
rounding = 4
gaps_in = 2
gaps_out = 2
keep_upper_gap = true
}
}