dwindle {
pseudotile = false
force_split = 0
preserve_split = true
smart_split = false
smart_resizing = true
special_scale_factor = 0.88
use_active_for_splits = true
default_split_ratio = 1.0
}
master {
mfact = 0.55
new_status = slave
orientation = left
inherit_fullscreen = true
always_center_master = false
smart_resizing = true
}
group {
insert_after_current = true
focus_removed_window = true
col.border_active = rgba(7c3aedff) rgba(2563ebff) 45deg
col.border_inactive = rgba(1c1c32ff)
groupbar {
enabled = true
font_family = JetBrainsMono Nerd Font
font_size = 10
gradients = true
render_titles = true
scrolling = true
text_color = rgba(cdd6f4ff)
col.active = rgba(7c3aed88)
col.inactive = rgba(1c1c3288)
height = 22
rounding = 4
}
}