windowrulev2 = noshadow, class:^(rofi)$
windowrulev2 = noshadow, class:^(wlogout)$
windowrulev2 = noshadow, class:^(dunst)$
windowrulev2 = noshadow, fullscreen:1
windowrulev2 = nodim, class:^(mpv)$
windowrulev2 = nodim, class:^(vlc)$
windowrulev2 = nodim, class:^(firefox)$
windowrulev2 = nodim, fullscreen:1
windowrulev2 = opacity 1.0 0.85, class:^(kitty)$
windowrulev2 = opacity 1.0 0.85, class:^(Alacritty)$
windowrulev2 = opacity 1.0 0.85, class:^(wezterm)$
windowrulev2 = opacity 1.0 0.90, class:^(code-url-handler)$
windowrulev2 = opacity 0.96 0.88, class:^(thunar)$
windowrulev2 = opacity 1.0 1.0, class:^(mpv)$
windowrulev2 = opacity 1.0 0.95, class:^(Spotify)$
windowrulev2 = noborder, fullscreen:1
windowrulev2 = noborder, class:^(steam_app_.*)$
windowrulev2 = rounding 0, fullscreen:1
windowrulev2 = rounding 18, class:^(pavucontrol)$
windowrulev2 = rounding 18, class:^(blueman-manager)$