#!/usr/bin/env bash
# Ultra-optimized WebP conversion pipeline for all desktop screenshots

set -euo pipefail

readonly DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Quality profiles
declare -A QUALITY_PROFILES=(
  ["preview"]="quality=75,method=4"
  ["standard"]="quality=88,method=5"
  ["premium"]="quality=92,method=6,sharp_yuv"
  ["lossless"]="lossless,exact"
)

convert_to_webp() {
  local input="$1"
  local profile="${2:-standard}"
  local base="${input%.*}"
  local output="${base}.webp"
  local thumb_output="${base}-thumb.webp"
  local params="${QUALITY_PROFILES[$profile]}"

  echo "  Converting: $(basename "$input") → $(basename "$output")"

  # Primary conversion
  if command -v cwebp &>/dev/null; then
    # Parse params
    local quality=88 method=5 sharp_yuv_flag=""
    [[ "$params" == *"sharp_yuv"* ]] && sharp_yuv_flag="-sharp_yuv"
    quality=$(echo "$params" | grep -oP 'quality=\K\d+' || echo 88)
    method=$(echo  "$params" | grep -oP 'method=\K\d+'  || echo 5)

    cwebp \
      -q "$quality" \
      -m "$method" \
      $sharp_yuv_flag \
      -metadata none \
      -hint photo \
      "$input" \
      -o "$output" 2>/dev/null

  elif command -v ffmpeg &>/dev/null; then
    ffmpeg -i "$input" \
           -vf "scale=2560:1440:flags=lanczos" \
           -c:v libwebp \
           -quality 88 \
           -compression_level 6 \
           "$output" -y 2>/dev/null
  fi

  # Thumbnail (640×360)
  if command -v convert &>/dev/null && [[ -f "$input" ]]; then
    mkdir -p "${DIR}/thumbnails"
    convert "$input" \
            -resize "640x360^" \
            -gravity center \
            -extent 640x360 \
            -sampling-factor 4:2:0 \
            "${DIR}/thumbnails/$(basename "$base")-thumb.webp"
  fi

  # AVIF variant (modern browsers)
  if command -v avifenc &>/dev/null; then
    mkdir -p "${DIR}/avif"
    avifenc \
      --min 20 --max 35 \
      --speed 4 \
      --jobs all \
      "$input" \
      "${DIR}/avif/$(basename "${base}").avif" 2>/dev/null
  fi

  # Report size
  if [[ -f "$output" ]]; then
    local orig_size web_size ratio
    orig_size=$(wc -c < "$input" 2>/dev/null || echo 0)
    web_size=$(wc -c < "$output" 2>/dev/null || echo 0)
    if [[ $orig_size -gt 0 ]]; then
      ratio=$(( web_size * 100 / orig_size ))
      printf "     %-32s %6s → %6s (%d%% of original)\n" \
             "$(basename "$output")" \
             "$(numfmt --to=iec "$orig_size" 2>/dev/null || echo "${orig_size}B")" \
             "$(numfmt --to=iec "$web_size"  2>/dev/null || echo "${web_size}B")" \
             "$ratio"
    fi
  fi
}

# Generate AVIF picture elements for HTML
generate_picture_elements() {
  local theme_name="$1"
  local display_name="$2"

  cat <<HTML
<picture class="ash-screenshot-preview" data-theme="${theme_name}">
  <!-- AVIF: best compression, modern browsers -->
  <source
    type="image/avif"
    srcset="avif/${theme_name}.avif 1x,
            avif/${theme_name}.avif 2x"
    media="(min-width: 640px)">

  <!-- WebP: wide browser support -->
  <source
    type="image/webp"
    srcset="${theme_name}.webp 1x,
            ${theme_name}.webp 2x"
    media="(min-width: 320px)">

  <!-- Thumbnail fallback -->
  <source
    type="image/webp"
    srcset="thumbnails/${theme_name}-thumb.webp"
    media="(max-width: 320px)">

  <!-- Final fallback -->
  <img
    src="${theme_name}.webp"
    alt="ASH Dotfiles — ${display_name} theme desktop screenshot"
    width="2560"
    height="1440"
    loading="lazy"
    decoding="async"
    class="ash-screenshot-preview__image"
    data-theme-name="${theme_name}"
    data-display-name="${display_name}">
</picture>
HTML
}

# Generate all picture elements
generate_all_html() {
  local output_file="${DIR}/gallery-snippets.html"
  cat > "$output_file" <<'HEADER'
<!-- ASH Dotfiles v5.0 — Screenshot Gallery HTML Snippets -->
<!-- Auto-generated by webp-optimizer.sh — DO NOT EDIT -->

<div class="ash-gallery-grid" id="ash-screenshot-gallery">
HEADER

  declare -A THEMES=(
    ["dark-catppuccin"]="Catppuccin Mocha"
    ["dark-tokyonight"]="Tokyo Night"
    ["dark-gruvbox"]="Gruvbox Dark"
    ["dark-nord"]="Nord"
    ["dark-dracula"]="Dracula"
    ["dark-onedark"]="One Dark"
    ["dark-everforest"]="Everforest Dark"
    ["dark-kanagawa"]="Kanagawa Wave"
    ["dark-rosepine"]="Rosé Pine"
    ["light-catppuccin"]="Catppuccin Latte"
    ["neon-cyberpunk"]="Cyberpunk 2077"
    ["neon-synthwave"]="Synthwave '84"
    ["nature-forest"]="Forest Deep"
    ["nature-ocean"]="Ocean Depth"
    ["space-nebula"]="Nebula Blue"
    ["retro-vaporwave"]="Vaporwave"
    ["anime-evangelion"]="Evangelion Unit-01"
  )

  for theme in "${!THEMES[@]}"; do
    generate_picture_elements "$theme" "${THEMES[$theme]}" >> "$output_file"
    echo "" >> "$output_file"
  done

  echo "</div>" >> "$output_file"
  echo "  ✅ Generated: ${output_file}"
}

# ── Main ───────────────────────────────────────────────────────────────
main() {
  echo ""
  echo "  ╔════════════════════════════════════════╗"
  echo "  ║   ASH WebP Optimizer v2.0              ║"
  echo "  ╚════════════════════════════════════════╝"
  echo ""

  local mode="${1:-convert}"

  case "$mode" in
    convert)
      echo "  🖼️  Converting PNG → WebP (premium quality)..."
      echo ""
      for png in "${DIR}"/*.png; do
        [[ -f "$png" ]] && convert_to_webp "$png" "premium"
      done
      ;;
    html)
      echo "  📄 Generating HTML picture elements..."
      generate_all_html
      ;;
    all)
      main convert
      main html
      ;;
    *)
      echo "  Usage: $0 [convert|html|all]"
      exit 1
      ;;
  esac

  echo ""
  echo "  ✅ Done"
}

main "$@"